### ISSUE TITLE
Templates are not installed under perlbrew

### ISSUE THREAD

**Issue by theory** [sqitchers/homebrew-sqitch#2]
From @heikkil  in theory/sqitch#92:

> I tried installing sqitch using homebrew (failed, not explored) and cpanm from perlbrew. The installation with perlbrew cpanm went without problems: all tests pass. However, the first tried command on command line, add, failed with
> "Cannot find deploy template"
> 
> Exactly the same happend when I cloned the repo. I am doing this on Mac OS X 10.7.5 and using Perl 10.5.18.0 from perlbrew. OS X does not have GNU gettext so it first has to be installed with homebrew and the binaries added to path: 
> export PATH=/usr/local/Cellar/gettext/0.18.2/bin:$PATH . 
> After that dzilla is able to build a distribution tarball that installs cleanly with cpanm.
> 
> Manually copying the templates, cp $REPOHOME/etc/templates $HOME/.sqitch/, fixes the problem.
> 
> The etc-path within sqitch seems to be totally wrong and couse of all the trouble:
> $ sqitch --etc-path
> .../../etc/sqitch
> 
> My hunch is that perlbrew installation has not been tested at all and that etc is not implemented in best possible way.

**Comment by charlesj** [comment]
Is there a solution to this now?  I just completed an install this morning and was walking through the tutorial and ran into this.  I'm on windows, running on activeperl, against postgres.

**Comment by theory** [comment]
@charlesj What's the output of `sqitch --etc-path`? If you copy the `etc` directory in the source repository to that spot it should start working properly.

**Comment by theory** [comment]
BTW, I switched to [Strawberry Perl](http://strawberryperl.com) for testing Sqitch on Windows last week. It takes a lot longer to install Sqitch (everything gets built from source), but then all the files are where they belong, including the template files.

**Comment by charlesj** [comment]
@theory the output of that command was a directory that didn't exist.  Instead of going further down that rabbit hole, I instead uninstalled ActivePerl and installed Strawberry Perl.  It wasn't too bad to install Sqitch - everything worked out of the box, and I was able to continue down the tutorial.  I ran into unrelated problems, but was able to successfully deploy out the schema change to the database, so I'm really happy.  The lesson in this case seems to be: use Strawberry Perl on Windows.

**Comment by theory** [comment]
Yeah, I'm finding Strawberry easier to deal with, as well, so I've added it to the [home page](http://sqitch.org/#windows).

**Comment by yati-sagade** [comment]
Hey! I am playing with sqitch for this month's CPAN PRC, and also had this issue on Fedora when using the git repo with `dzil install`. I see that the templates dir is copied to `~/perl5/etc/`, so maybe in this case all that is needed is to have `dzil` set the correct prefix for `App::Sqitch::Config`? :)
