### ISSUE TITLE
mysql not found

### ISSUE THREAD

**Issue by SheriefAlaa** [sqitchers/homebrew-sqitch#20]
Apparently the script doesn't detect that mysql is already installed on the system with the appropriate env var installed. Plus it's downloading from a non-existent link.

> [~] $ mysql
> ERROR 1045 (28000): Access denied for user 'sherief'@'localhost' (using password: NO)
> [~] $ brew install sqitch_mysql --verbose
> ==> Installing sqitch_mysql from theory/homebrew-sqitch
> ==> Installing sqitch_mysql dependency: mysql
> ==> Downloading http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.22.tar.gz
> /usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-645; Mac OS X 10.11.3) http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.22.tar.gz -C 0 -o /Library/Caches/Homebrew/mysql-5.6.22.tar.gz.incomplete
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
> Error: Failed to download resource "mysql"
> Download failed: http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.22.tar.gz

**Comment by theory** [comment]
No, it wants the Homebrew MySQL. I don't know whether it will work with a non-Homebrew MySQL, but maybe just try commenting out the requirement for mysql in `sqitch_mysql.rb` and try again.

**Comment by theory** [comment]
In the new formula, release last night for v0.9998, you can build Sqitch with MySQL support without requiring the Homebrew MySQL package like so:

```
brew install sqitch --with-mysql-support --without-mysql
```
 
That keeps things nice and explicit, so you can easily keep using your own copy of MySQL.
