### ISSUE TITLE
Sqitch installation broke vim

### ISSUE THREAD

**Issue by wkoszek** [sqitchers/homebrew-sqitch#47]
After adding the tap, I installed `sqitch` on my Mac Mini with Catalina.

Command used:

```
brew install sqitch --with-postgres-support --with-sqlite-support
```

It ended up with vim 

```
hint: Waiting for your editor to close the file... dyld: Library not loaded: /usr/local/opt/perl/lib/perl5/5.30.1/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /usr/local/bin/vim
  Reason: image not found
error: vim died of signal 6
error: There was a problem with the editor 'vim'.
Please supply the message using either -m or -F option.
```

Reinstalling Vim seems to make it work again, but decided to report it again.

**Comment by theory** [comment]
Odd. What's just above that error? Sqitch doesn't use vim for anything, so I wonder if one of its dependencies does.

**Comment by wkoszek** [comment]
Yeah, it's a perl dependency that got messed up. It's a little surprising. I'd not be surprised if it's somehow a brew problem (almost looks like it took a vim's dependency, uninstalled/updated it). Can't really explain it.

**Comment by theory** [comment]
Okay, closing, then, thanks.
