### ISSUE TITLE
brew update leads to missing ref

### ISSUE THREAD

**Issue by unitof** [sqitchers/homebrew-sqitch#48]
Recently running `brew update` started causing the following error:

```
fatal: couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/sqitchers/homebrew-sqitch failed!
```

**I figured out why and am posting the solution to help others:**

Sqitch recently renamed the `master` branch to `main` (including this this very repo!). Homebrew relies on local Git origin settings for each tap so it's still looking for the old branch on `origin`.

Just run:

```
brew untap sqitchers/sqitch && brew tap sqitchers/sqitch
```

and you'll be good to go!

Note that untapping does **not** uninstall or erase any Sqitch settings, just refreshes the Homebrew tap. I could only see this causing an issue if you've been doing local edits in `/usr/local/Homebrew/Library/Taps/sqitchers/homebrew-sqitch`, in which case you could manually edit `.git/config` to reflect the new `origin:main` branch.

**Comment by unitof** [comment]
Sqitch crew: it may be helpful if, like Twilio after also renaming, you added a `Warning` to Homebrew to alert users what they need to do.

I…have no idea how you do that but I'm sure you'll figure it out!

<img width="994" alt="image" src="https://user-images.githubusercontent.com/2448782/89810242-bde0be80-db0a-11ea-8f16-14fc2e73688b.png">

**Comment by unitof** [comment]
Found out how you do it! You'd have to (temporarily) recreate the `master` branch with something like this: https://github.com/twilio/homebrew-brew/commit/01eab759195891101f11497b6af7fe074abba79b

**Comment by theory** [comment]
Good call, thanks @unitof.

**Comment by altfatterz** [comment]
```
brew tap --repair
```
