### ISSUE TITLE
Installing the dependencies failed: Module 'IO::Pager' is not installed

### ISSUE THREAD

**Issue by YunaBraska** [sqitchers/homebrew-sqitch#50]
### Error
`Installing the dependencies failed: Module 'IO::Pager' is not installed`

### Steps to reproduce
* `brew tap sqitchers/sqitch`
* `brew install sqitch --with-postgres-support`

### Versions
* MacOs 10.15.7
* Homebrew 2.5.8
* Perl v5.32.0 (System)

### Steps tried
* cpanm IO::Pager 
```
IO::Pager is up to date. (2.01)
```
* sudo cpanm IO::Pager --force
```
Successfully reinstalled IO-Pager-2.01
1 distribution installed
```
* sudo perl -MCPAN -e 'install IO::Pager'
```
/usr/bin/make install  -- OK
```

### Log output
```bash
Updating Homebrew...
==> Installing sqitch from sqitchers/sqitch
==> Downloading https://www.cpan.org/authors/id/D/DW/DWHEELER/App-Sqitch-v1.1.0.tar.gz
Already downloaded: /Users/yunamorgenstern/Library/Caches/Homebrew/downloads/f1ebd13dbda2c5ad95c6f9f14278d7771011f3d113aaa624d6fb79e78bd7fb3c--App-Sqitch-v1.1.0.tar.gz
==> cpanm --local-lib instutil --quiet --notest Menlo::CLI::Compat Module::Build
==> perl Build.PL --quiet --install_base /usr/local/Cellar/sqitch/v1.1.0 --etcdir /usr/local/etc/sqitch --with postgres
==> ./Build bundle
Last 15 lines from /Users/yunamorgenstern/Library/Logs/Homebrew/sqitch/03.Build:
Successfully installed DateTime-1.52
! Configure failed for Module-Signature-0.87. See /private/tmp/sqitch-20201103-80027-19smwvh/App-Sqitch-v1.1.0/.brew_home/.cpanm/work/1604399594.87382/build.log for details.
Successfully installed DBD-Pg-3.14.2
Successfully installed URI-Nested-0.10
Successfully installed URI-db-0.19
Successfully installed libintl-perl-1.32
Successfully installed Clone-Choose-0.010
Successfully installed Hash-Merge-0.302
Successfully installed String-ShellQuote-1.04
Successfully installed AppConfig-1.71
Successfully installed Template-Toolkit-3.009
! Installing the dependencies failed: Module 'IO::Pager' is not installed
! Bailing out the installation for App-Sqitch-v1.1.0.
Error installing modules: 
88 distributions installed

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sqitchers/homebrew-sqitch/issues

These open issues may also help:
After brew install sqitch --with-postgres-support, error deploying https://github.com/sqitchers/homebrew-sqitch/issues/46
Failing to brew install sqitch--with-postgres-support --without-postgresql https://github.com/sqitchers/homebrew-sqitch/issues/45
```

**Comment by sminutoli** [comment]
@YunaBraska I'm having the SAME issue

**Comment by aailenm** [comment]
Me too

**Comment by sminutoli** [comment]
@YunaBraska we could manage to fix it installing `sqitch` from Perl, and then making an alias pointing to the bin...

```
cpan install App::Sqitch DBD::Pg
cd /usr/local/bin && ln -s /usr/local/Cellar/perl/5.32.0/bin/sqitch
```

**Comment by theory** [comment]
It's so annoying when a module installation fails. Something must've changed with IO::Pager or one of its dependencies. I've replicated the issue, attempting to get to the root of it.

**Comment by AndrewCathcart** [comment]
I imagine it's probably best to wait until you've resolved it, rather than trying @sminutoli 's approach @theory ? All the best.

**Comment by theory** [comment]
I found the issue; it's a [bug in IO-Pager](https://rt.cpan.org/Public/Bug/Display.html?id=133674). Hopefully they will fix it soon; in the meantime, the workaround might be for the best.

**Comment by AndrewCathcart** [comment]
Good to know. Thanks for figuring it out so swiftly.

Tried @sminutoli 's approach (using the Snowflake driver instead of Postgres) and can confirm that worked! Didn't need to use sudo however.

As an aside, crazy how long it takes to install from cpan rather than through homebrew.

**Comment by theory** [comment]
Well I taught `./Build bundle` (used by Homebrew) not to run tests while installing dependencies. That makes a _huge_ difference.

**Comment by theory** [comment]
Looks like [IO::Pager 2.10](https://metacpan.org/release/JPIERCE/IO-Pager-2.10) is making its way to the CPAN mirrors now, so should be all better for most folks within a few hours. Thank you for your patience.
