### ISSUE TITLE
Sqitch has stopped running

### ISSUE THREAD

**Issue by neilprosser** [sqitchers/homebrew-sqitch#60]
I'm trying to work out whether I've had this work since I upgraded to Sonoma. I feel like I have but can't be sure.

Here's the error I'm seeing:

```shell
$ sqitch
/opt/homebrew/bin/sqitch: /opt/homebrew/Cellar/sqitch/v1.4.0/libexec/sqitch: /opt/homebrew/Cellar/perl/5.36.1/bin/perl: bad interpreter: No such file or directory
/opt/homebrew/bin/sqitch: line 2: /opt/homebrew/Cellar/sqitch/v1.4.0/libexec/sqitch: Undefined error: 0
```

I assume there will be more questions so please let me know what other information you need!

**Comment by theory** [comment]
Sounds like Perl has been removed, or maybe upgraded to a new version and moved? Try reinstalling Sqitch. IIRC It's `brew reinstall sqitch`.

**Comment by neilprosser** [comment]
Thanks! That makes sense. I'd tried reinstalling but had used an alias which does something different so didn't actually reinstall.

`brew reinstall sqitch` worked like a charm!
