### ISSUE TITLE
Option to exclude installation of PostgreSQL client library does not seem to exist

### ISSUE THREAD

**Issue by mattdeluco** [sqitchers/homebrew-sqitch#62]
When trying to execute the following Homebrew installation command I ended up with an error:
`brew install sqitch --with-postgres-support --without-postgresql`

Results in:
```
Error: invalid option: --without-postgresql
Did you mean?  with-mysql-support
```

Perusing the usage documentation that was also output, the option `--without-postgresql` does not seem to exist (I didn't see any "without" options.)

**Comment by theory** [comment]
Hrm, that's a Homebrew-specific option. I wonder if they removed it.

**Comment by robahtou** [comment]
Any update on this? same issue.

**Comment by theory** [comment]
Started a [discussion topic](/orgs/Homebrew/discussions/5428) to get to the bottom of it. But also, as of 8167e40, the formula no longer depends on the `mysql` or `postgresql` formulas, preferring instead just to install the client libraries and CLIs.

**Comment by gromgit** [comment]
Homebrew banned options in all core formulae **years** ago.

Options _support_ in `brew`, however, remains intact, and third-party taps are free to include as many options in their formulae as deemed necessary.

**Comment by theory** [comment]
Thanks. Interesting that no one complained about it to me until _this year_.

Solution will be to add options that have the equivalent functionality I guess. Thanks.

**Comment by theory** [comment]
Removing documentation of the `--without-*` options in #63.
